### ISSUE TITLE
LLVM 5.0 is now the master branch

### ISSUE THREAD

**Issue by ianamason** [SRI-CSL/OCCAM#13]
- [ ] We need to build 5.0 and fudge a travis install
- [ ] Fix travis for all the older LLVM version branches that are failing.
- [ ] Argv specialization
- [ ] razor (aka slash) not picking the right clang++
- [ ] hello vs argv small perturbation in the C causing crashes

**Comment by caballa** [comment]
@ianamason : What is the status of this?
travis seems to work. We don't need to fix travis for older LLVM versions. What about the rest?
