### ISSUE TITLE
No specialization of internal functions?

### ISSUE THREAD

**Issue by caballa** [SRI-CSL/OCCAM#16]
It seems that OCCAM doesn't specialize a function call if the function is defined in the same module that the call. This is done in `src/StrategySpecializer.cpp` at line 123. 

We should have at least a flag to allow users to decide.

**Comment by ianamason** [comment]
Can never have enough flags.

**Comment by caballa** [comment]
OCCAM has new flags to choose whether enabling or not specialization of both inter-module and intra-module callsites. The user can also choose the kind of specialization policy.
