### ISSUE TITLE
`examples/portfolio/apache` linking error on Mac

### ISSUE THREAD

**Issue by caballa** [SRI-CSL/OCCAM#22]
It cannot find `libcrypt`:
```
 ld: library not found for -lcrypt
```

Should we only run this program on Linux?

**Comment by ianamason** [comment]
No I think this used to work. I will look into it.

**Comment by ianamason** [comment]
This still builds for me, so it must be picking up a homebrew version of libcrypt.

If this is needed @caballa  then we would have to either build openssl or install it.

One solution would be to include the openssl build from the openssh example.
And use that. apache does not have explicit configure stuff for openssl so I guess we
would have to use LDFLAGS.

Which route?

**Comment by caballa** [comment]
Sorry, apache builds without any problem. The linking error is when I try to build the slashed version (i.e., after I run OCCAM)
