### ISSUE TITLE
Error which running an example in the docker

### ISSUE THREAD

**Issue by Mohannadcse** [SRI-CSL/OCCAM#27]
I received the following error while running the argv example 

![image](https://user-images.githubusercontent.com/15859139/78196488-2bd3f580-7448-11ea-9721-945525708eab.png)

**Comment by caballa** [comment]
The manifest was using old format. The manifest has been updated to current format in ce80ebb2cb6cf0ecaa09f9dbc7b55b66f2a42885

**Comment by Mohannadcse** [comment]
Much appreciated. Works now.
