### ISSUE TITLE
slash Command not found

### ISSUE THREAD

**Issue by Mohannadcse** [SRI-CSL/OCCAM#28]
I built OCCAM according to the provided instruction. But I receive the following error `make: slash: Command not found` when I try to run any of the examples. Where I installed razor and configured OCCAM_HOME.

**Comment by ianamason** [comment]
Clearly `slash` is not in your `PATH`.   Where did you install it?  Maybe add that location to your `PATH`?

**Comment by Mohannadcse** [comment]
I think slash supposed to be installed while building OCCAM. But I already installed razor using the command `pip install razor` as shown below. Is there a specific instruction other than the `pip install razor` command?

![image](https://user-images.githubusercontent.com/15859139/79280105-2679a080-7e75-11ea-8e48-fcad8f3d63bf.png)

**Comment by ianamason** [comment]
No, take a look at the top level makefile. It does a pip install. Make sure your pip is the same as the python you are running.

**Comment by Mohannadcse** [comment]
The make log shows the following

![image](https://user-images.githubusercontent.com/15859139/79280706-a9e7c180-7e76-11ea-949c-08b18ce3f7bc.png)

So I'm not quite sure where the make has installed slash

**Comment by ianamason** [comment]
That '2.7' in the path look pretty scary if you are using python 3.

**Comment by ianamason** [comment]
The makefile uses pip to install it, but maybe it is picking up the 2.7 version?

**Comment by Mohannadcse** [comment]
Seems so. So python3 should be used, right?

**Comment by ianamason** [comment]
Well I think you can use both, but it has been a long time since I did any OCCAM work. @caballa does OCCAM (in particular slash) work with 3, you were having some issues a while back, I recall?

Either way you have to use the same version to install and run it ...

**Comment by Mohannadcse** [comment]
Thank you I fixed it. As you pointed out, there was inconsistency in the Python version.

**Comment by ianamason** [comment]
Great. Not a fan of python for that very reason.
