### ISSUE TITLE
gzip issue 

### ISSUE THREAD

**Issue by shoaibCS** [SRI-CSL/OCCAM#32]
I ran **OCCAM** on **gzip**. OCCAM stopped with an error message. I am sharing the error message towards the end. From error message, it appears that the error condition gets triggered when "Compare Call Graph SeaDsa pass" is invoked.

In order to replicate the error, download the **gzip-1.3.12.zip** from this [link](https://drive.google.com/file/d/1APPYmfLguukbR3ska2icccm-P68GvQXk/view?usp=sharing). Then, unzip it and run `bash run.sh` within **gzip-1.3.12**.  you will then see the error message shown below.

```
opt: sea-dsa/lib/seadsa/DsaLocal.cc:906: void (anonymous namespace)::BlockBuilderBase::visitGep(const llvm::Value &, const llvm::Value &, ArrayRef<llvm::Value *>): Assertion `false && "No cell for gep'd ptr"' failed.
Stack dump:
0.	Program arguments: /usr/lib/llvm-10/bin/opt -load=/occam/lib/libSeaDsa.so -load=/occam/lib/libprevirt.so /occam/paper_data/occam_number_trimmer/examples/gzip_objdump_aircrack/gzip-1.3.12/slash/gzip.a.i.p.bc -o=/dev/null -Pinterface -Pinterface-with-seadsa --sea-dsa-type-aware=true -Pinterface-output /tmp/tmp1lp7zu.iface -Pinterface-entry /tmp/tmp1lp7zu.iface 
1.	Running pass 'Complete Call Graph SeaDsa pass' on module '/occam/paper_data/occam_number_trimmer/examples/gzip_objdump_aircrack/gzip-1.3.12/slash/gzip.a.i.p.bc'.
```

**Comment by caballa** [comment]
Update OCCAM and `src/analysis/sea-dsa`

**Comment by shoaibCS** [comment]
Thanks for helping, the issue got resolved.
