### ISSUE TITLE
`razor` pypi package does not work with python3

### ISSUE THREAD

**Issue by pnwamk** [SRI-CSL/OCCAM#38]
The PyPI page for [razor](https://pypi.org/project/razor/) suggests it should work with Python 3, but trying to run `slash` after installing it results in errors:

```
$ slash
Traceback (most recent call last):
  File "/usr/local/bin/slash", line 5, in <module>
    from razor.slash import entrypoint
  File "/usr/local/lib/python3.8/site-packages/razor/slash.py", line 200
    if policy <> 'none' and \
               ^
SyntaxError: invalid syntax
```

For this error I believe it's that the `<>` operator existed as an alternative to `!=` in [Python2](https://docs.python.org/2.7/reference/lexical_analysis.html#operators) but for Python 3 `!=` is the only such [comparison operator](https://docs.python.org/3/reference/expressions.html#comparisons). I haven't checked for other incompatibilities.

**Comment by pnwamk** [comment]
This has been made worse given that recent versions of pip have completely dropped support for python 2.7 and introduce some interesting dynamic failures instead.

For anyone reading and curious: on MacOS, first running `sudo easy_install pip==20.3.4` (i.e., installing a version of `pip` that works with python 2.7) and then running `python2.7 -m pip install razor` successfully has installed `razor` and the `slash` command now works as expected so far.

**Comment by caballa** [comment]
We have just ported razor to python 3.6
Let me know if you encounter any problem. 

Thanks for reminding us to port razor!
