### ISSUE TITLE
Segmentation fault in netperf after specialization with OCCAM

### ISSUE THREAD

**Issue by mudbri** [SRI-CSL/OCCAM#42]
Running the specialized binary for netperf-2.4.3 results in a segmentation fault. The attached  
[netperf.zip](https://github.com/SRI-CSL/OCCAM/files/6328294/netperf.zip)
contains the compressed tar containing the source code for netperf-2.4.3, Makefile, and manifest file.

To reproduce the issue, run:
1. **make**
2. **slash --work-dir=slash --disable-inlining --inter-spec-policy=none --intra-spec-policy=onlyonce --use-pointer-analysis netperf.manifest**
3. **cd slash** and then **./netperf_fin**

**Comment by caballa** [comment]
Fixed in commit 07241b3fad62eaa280b80e4801da229fd1a3a475

**Comment by mudbri** [comment]
Checked. The specialization occurs without any errors and the specialized binary is working correctly in the latest commit. Thanks!
