### ISSUE TITLE
Specialization fails to complete with configuration priming: httping

### ISSUE THREAD

**Issue by mudbri** [SRI-CSL/OCCAM#43]
I encounter a segmentation fault when I run slash with configuration priming on httping-2.4. The tar file for httping-2.4, make file to get bitcode, OCCAM log file, and manifest file is included in the zip: 
[httping_config_issue.zip](https://github.com/SRI-CSL/OCCAM/files/6620074/httping_config_issue.zip)

The issue can be reproduced in the following way:
1. **make** (this might require installing gettext i.e. `apt-get install gettext`)
2. **slash --work-dir=slash_config --enable-config-prime  --disable-inlining --inter-spec-policy=none --intra-spec-policy=onlyonce --use-pointer-analysis httping.manifest**

Note: The specialization is successful if we don't use the **--enable-config-prime** flag with slash.
Error: 

> Traceback (most recent call last):
>   File "/home/vagrant/.local/bin/slash", line 33, in <module>
>     sys.exit(load_entry_point('razor==1.1.2', 'console_scripts', 'slash')())
>   File "/home/vagrant/.local/lib/python3.6/site-packages/razor/slash.py", line 103, in entrypoint
>     return Slash(sys.argv).run() if utils.checkOccamLib() else 1
>   File "/home/vagrant/.local/lib/python3.6/site-packages/razor/slash.py", line 368, in run
>     passes.config_prime(pre, post, list(), dynamic_args)
>   File "/home/vagrant/.local/lib/python3.6/site-packages/razor/passes.py", line 434, in config_prime
>     driver.previrt(input_file, output_file, args)
>   File "/home/vagrant/.local/lib/python3.6/site-packages/razor/driver.py", line 75, in previrt
>     return run(config.get_llvm_tool('opt'), args, **opts)
>   File "/home/vagrant/.local/lib/python3.6/site-packages/razor/driver.py", line 173, in run
>     raise ex
> razor.driver.ReturnCode: /usr/lib/llvm-10/bin/opt -load=/home/vagrant/occam/lib/libSeaDsa.so -load=/home/vagrant/occam/lib/libprevirt.so /home/vagrant/realTrimmer/Trimmer/examples/httping-2.4/slash_config/httping.a.bc -o=/home/vagrant/realTrimmer/Trimmer/examples/httping-2.4/slash_config/httping.a.cp.bc -O1 -Pconfig-prime -Pconfig-prime-unknown-args=1
> returned -11

**Comment by caballa** [comment]
This should be fixed in commit c3069fbf2df3ca2aeedbef96b77b59a6e9c64e27
