### ISSUE TITLE
Unexpected output with specialized binary using configuration priming: wget, dnsproxy, sans, totd

### ISSUE THREAD

**Issue by mudbri** [SRI-CSL/OCCAM#48]
The following 4 applications work incorrectly when specialized with the --enable-config-prime flag: wget, dnsproxy, sans, totd. All four applications use a configuration file as a static argument in their manifests. All the required files for reproduction are attached [here](https://github.com/SRI-CSL/OCCAM/files/6760589/examples_with_config_files.zip). The issues can be reproduced in the following way:

1. **cd [application name]**
2. **make** (The following dependencies might be required: apt-get install autoconf libpcre3-dev libpcre3)
3. **bash build.sh --enable-config-prime**
4. **make test**

The tests for all four applications fail with the --enable-config-prime flag provided. However, the tests pass if the flag is not provided  (i.e.  **bash build.sh**).

**Comment by caballa** [comment]
I list here the four benchmarks to follow the progress:

- [ ] wget
- [ ] dnsproxy
- [ ] sans
- [ ] totd

**Comment by caballa** [comment]
wget is fixed in commit ca2e84536c7d356af439634de0fb2900db1f622e.

@mudbri : would you mind to check the other three programs?

**Comment by mudbri** [comment]
Thanks! wget and dnsproxy are fixed now but sans and totd are still not working correctly. 
The sudo to run test_totd.py can be removed. The test should work fine without it

**Comment by caballa** [comment]
The reason for the crashes in `sans` and `totd` is explained in issue #54.

**Comment by caballa** [comment]
sans and totd works fine after commit 948ca531cc56959986521b1fb7adff0b0cdac44c
