### ISSUE TITLE
Specialized binary does not give any output with configuration priming: airtun

### ISSUE THREAD

**Issue by mudbri** [SRI-CSL/OCCAM#49]
Specializing airtun with configuration priming results in a large reduction of functions. However, the specialized binary does not give any output. The files required to reproduce the problem can be found [here](https://github.com/SRI-CSL/OCCAM/files/6760598/airtun_config_prime_issue.zip). The issue can be reproduced in the following way:

1. **cd airtun**
2. **make** (the following dependency might be required: apt-get install libssl-dev)
3. **bash build.sh --enable-config-prime**
4. **make test**

The test compares the output of the specialized binary with that of the unspecialized one. The test fails when the --enable-config-prime flag is provided. However, the test passes when the flag is not provided  (i.e.  **bash build.sh**).

**Comment by caballa** [comment]
It should be fixed in commit ca2e84536c7d356af439634de0fb2900db1f622e
