### ISSUE TITLE
Specialized binary results in a runtime segmentation fault with configuration priming: netperf

### ISSUE THREAD

**Issue by mudbri** [SRI-CSL/OCCAM#50]
The specialized binary of netperf, when specialized with configuration priming, outputs a segmentation fault when run. The files required to reproduce the problem can be found [here](https://github.com/SRI-CSL/OCCAM/files/6760618/netperf_config_prime_issue.zip). The issue can be reproduced in the following way:

1. **cd netperf**
2. **make** 
3. **bash build.sh --enable-config-prime**
4. **make test**

The test compares the output of the specialized binary with the correct output. The test fails when the --enable-config-prime flag is provided. However, the test passes when the flag is not provided  (i.e.  **bash build.sh**). To see the segmentation fault, run **./netperf_slashed_stripped** (after running bash build.sh --enable-config-prime).

**Comment by caballa** [comment]
The reason for the crash is explained in issue #54

**Comment by caballa** [comment]
Fixed in commit 068140023ca11af3ee00bdb0fbc4e050382ed220
