### ISSUE TITLE
Specialized binary gives incorrect output with configuration priming: gzip

### ISSUE THREAD

**Issue by mudbri** [SRI-CSL/OCCAM#51]
The specialized binary of gzip, when specialized with configuration priming, results in an incorrect output. The files required to reproduce the problem can be found [here](https://github.com/SRI-CSL/OCCAM/files/6760644/gzip_config_prime_issue.zip). The issue can be reproduced in the following way:

1. **cd gzip**
2. **make** (The following dependency might be required: apt-get install libbz2-dev)
3. **bash build.sh --enable-config-prime**
4. **make test**

The test compares a file compressed with the specialized binary against the same file compressed with the unspecialized binary. The test fails when the --enable-config-prime flag is provided. It repeatedly outputs the following: `gzip: huffman.c: No such file or directory`. However, the test passes when the flag is not provided  (i.e.  **bash build.sh**).

**Comment by caballa** [comment]
It should be fixed in commit ca2e84536c7d356af439634de0fb2900db1f622e
