### ISSUE TITLE
Minor issue with redirection in the specialized binary (with configuration priming): curl

### ISSUE THREAD

**Issue by mudbri** [SRI-CSL/OCCAM#53]
When curl is specialized with configuration priming, it results in a working binary. However, when the the output of the binary is redirected to a file, a segmentation fault occurs. This fault does not occur when configuration priming is not turned on. Files to reproduce the issue can be found [here](https://github.com/SRI-CSL/OCCAM/files/6760677/curl_config_prime_issue.zip). The issue can be reproduced in the following steps:

1. **cd curl**
2. **make** (This might require installing openssl-1.0.2 using `bash install_dependencies.sh`) 
3. **bash build.sh --enable-config-prime**
4. **./curl_occamized_stripped https://www.sri.com > t_out**

This will result in a segmentation fault. However, when "> t_out" is removed, we get the expected output. If the --enable-config-prime flag is not used, there are no issues with redirection. This can be confirmed by running the test: make test

**Comment by caballa** [comment]
The reason for the crash is explained in issue #54

**Comment by caballa** [comment]
Fixed in commit a34876418efcc2d5f7f92cd44520a8001ca4117e
